FROM node:latest as base
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .

ENV NODE_PATH=./build
ENV NODE_ENV=production
RUN npm run build
RUN npm install --production --silent
EXPOSE 3001
CMD ["npm", "run", "server"]