version: '3.7'

services:
  chinatownsoundmapapi:
    image: chinatownsoundmapapi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3001:3001
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "./bin/www"]
